logging:
  level: INFO
  loggers:
    com.motivity: DEBUG

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: root
  url: jdbc:mysql://localhost:3306/motivity
  properties:
     hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
     hibernate.ddl-auto: update
     hibernate.show_sql: true
     hibernate.format_sql: true
     hibernate.use_sql_comments: true